stages:
- setup
- build
- deploy

# composer install dependencies
build-composer:
  stage: setup
  image: edbizarro/gitlab-ci-pipeline-php:latest
  script:
    - composer install --no-dev --prefer-dist --no-interaction
  artifacts:
    name: "$CI_BUILD_REF"
    untracked: true
    paths:
      - vendor
    expire_in: 1 week

build-npm:
  stage: build
  image: node:latest
  cache:
    paths:
     - node_modules/
  before_script:
    - npm install -g gulp-cli
    - npm install
  script:
    - npm run build
  artifacts:
      name: "$CI_BUILD_REF"
      untracked: true
      paths:
        - public
      expire_in: 1 week


stage:
  stage: deploy
  image: nilportugues/ansistrano
  before_script:
    # Install ssh-agent if not already installed, it is required by Docker.
    # (change apt-get to yum if you use a CentOS-based image)
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

    # Run ssh-agent (inside the build environment)
    - eval $(ssh-agent -s)

    # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    - ssh-add <(echo "$SSH_PRIVATE_KEY")

  script:
    - cd deploy/playbook
    - ansible-playbook -i hosts.yml deploy.yml --extra-vars "ansible_host=${DEPLOY_TARGET_HOST} ansible_user=${DEPLOY_TARGET_USER} ansistrano_deploy_to=${ANSIBLE_STAGE_PATH}"
  environment:
    name: stage
    url: ${STAGE_URL}
  variables:
    ansible_ssh_private_key_file: ~/.ssh/remote_key
    DEPLOY_TARGET_PATH: ${ANSIBLE_STAGE_PATH}
    ansible_user: ${DEPLOY_TARGET_USER}
    ansible_host: ${DEPLOY_TARGET_HOST}
    ansistrano_deploy_to: ${ANSIBLE_STAGE_PATH}
  only:
    - develop


production:
  stage: deploy
  image: nilportugues/ansistrano
  before_script:
     # Install ssh-agent if not already installed, it is required by Docker.
     # (change apt-get to yum if you use a CentOS-based image)
     - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

     # Run ssh-agent (inside the build environment)
     - eval $(ssh-agent -s)

     # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
     - ssh-add <(echo "$SSH_PRIVATE_KEY")
  script:
    - cd deploy/playbook
    - ansible-playbook -i hosts.yml deploy.yml --extra-vars "ansible_host=${DEPLOY_TARGET_HOST} ansible_user=${DEPLOY_TARGET_USER} ansistrano_deploy_to=${ANSIBLE_PROD_PATH}"
  environment:
    name: production
    url: ${PROD_URL}
  variables:
    ansible_ssh_private_key_file: ~/.ssh/remote_key
    DEPLOY_TARGET_PATH: ${ANSIBLE_PROD_PATH}
    ansible_user: ${DEPLOY_TARGET_USER}
    ansible_host: ${DEPLOY_TARGET_HOST}
    ansistrano_deploy_to: ${ANSIBLE_PROD_PATH}
  only:
    - master
